##..................................................................................
## data manipulation and handling
##..................................................................................
## Returns a logical vector TRUE for elements of X not in Y
`%nin%` <- function(x, y) !(x %in% y)
