##..................................................................................
## reporting inkl formatieren mit knitr & co
##..................................................................................
### copy to the clipboard
ccc <- function(x)write.table(x, "clipboard",sep="\t",row.names=F)
